import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { sohne } from './fonts'
import Navigation from "@/app/components/Navigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home | Muse Land",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sohne.variable}>
      <body
        className={`antialiased ${sohne.className}`}
      >
        <Navigation />
        <main className={''}>
            <div>
                {children}
            </div>
        </main>
      </body>
    </html>
  );
}
