import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { sohne } from './fonts'
import Navigation from "@/app/components/Navigation";
import Footer from "@/app/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home | Muse Land",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={sohne.variable}>
            <body className={`antialiased flex flex-col justify-start min-h-screen ${sohne.className}`}>
                <Navigation/>
                <main>
                    <div>
                        {children}
                    </div>
                </main>
                <Footer/>
            </body>
        </html>
    );
}
