import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home | Lands",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased flex flex-col justify-start min-h-screen`}>
                {children}
            </body>
        </html>
    );
}
